/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;

public class AutoLayoutViewManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & AutoLayoutViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public AutoLayoutViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "horizontal":
        mViewManager.setHorizontal(view, value == null ? false : (boolean) value);
        break;
      case "scrollOffset":
        mViewManager.setScrollOffset(view, value == null ? 0f : ((Double) value).doubleValue());
        break;
      case "windowSize":
        mViewManager.setWindowSize(view, value == null ? 0f : ((Double) value).doubleValue());
        break;
      case "renderAheadOffset":
        mViewManager.setRenderAheadOffset(view, value == null ? 0f : ((Double) value).doubleValue());
        break;
      case "enableInstrumentation":
        mViewManager.setEnableInstrumentation(view, value == null ? false : (boolean) value);
        break;
      case "disableAutoLayout":
        mViewManager.setDisableAutoLayout(view, value == null ? false : (boolean) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }
}
