module.exports = {

  // This for the alphabetical autogenerated sidebar
  autoSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Uncomment this if not using the auto sidebar above
  // Uses the docusaurus/docs directory by default as the root of the docs
  
  // This is an example of what the manual sidebar should look like
  /*
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Navigation',
      collapsible: true,
      collapsed: true,
      // Add these as an array
      items: [
        'nav/nav',
        'nav/text'
      ],
    },
  ],
  */

};

